# -*- coding: utf-8 -*-
"""CV_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dDKM-tyVJh4TIlIMsiqtM42zeNse-xT
"""

import cv2
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt
import tracemalloc
import math
import numpy as np

def chroma_key(img_input, img_chromakey, color2change, treshold):
  """
  color2change: BGR!!!
  """
  if img_input.shape != img_chromakey.shape:
    raise TypeError(f"incorrect size: {img_input.shape} != {img_chromakey.shape}")
  rows_len = img_input.shape[0]
  columns_len = img_input.shape[1]
  for row in range(rows_len):
    for column in range(columns_len):
      pixel = img_input[row][column]
      pixel2 = img_chromakey[row][column]

      if math.dist(pixel, color2change) < treshold:
        img_input[row][column] = img_chromakey[row][column]
  return img_input

path_input = r"/content/drive/MyDrive/CV/шалунишки.jpg"
path_output = r"/content/drive/MyDrive/CV/типо_на_конференции.jpg"

"""### пример использования"""

custom_change_color = (204, 222, 233) #BGR

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))

imgfinal = chroma_key(img_inp, img_back, (0, 255, 0), 40)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо замены зеленого:)")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 40)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 5)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне порог 2:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 10)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне порог 10:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 15)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне порог 15:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 20)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне порог 20:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(path_output)
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 60)
plt.imshow(imgfinal[:,:,::-1])
plt.title("Демо на фоне порог 100:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(r"/content/drive/MyDrive/CV/типо_в_экане.jpg")
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 40)
plt.imshow(imgfinal[:,:,::-1])
plt.title("В ЭКАНЕ?!:")
plt.show()

img_inp = cv2.imread(path_input)
img_back = cv2.imread(r"/content/drive/MyDrive/CV/типо_в_экане_2.jpg")
img_back = cv2.resize(img_back, (img_inp.shape[1], img_inp.shape[0]))
imgfinal = chroma_key(img_inp, img_back, custom_change_color, 40)
plt.imshow(imgfinal[:,:,::-1])
plt.title("В ЭКАНЕ?!:")
plt.show()

"""### Пример замера времени"""

tracemalloc.start()
chroma_key(img_inp, img_back, custom_change_color, 40)
current, peak = tracemalloc.get_traced_memory()
print(f"Current: {current / 1024 / 1024:.2f} MB, Peak: {peak / 1024 / 1024:.2f} MB")
tracemalloc.stop()

"""### Запуск на 100 фотках"""

path_input = r"/content/drive/MyDrive/CV/шалунишки.jpg"
path_output = r"/content/drive/MyDrive/CV/типо_на_конференции.jpg"

result_df = {}

import timeit
from copy import deepcopy
from tqdm import tqdm
import pandas as pd

img_interest_size = range(10, 1000, 10)
img_inp_o = cv2.imread(path_input)
img_back_o = cv2.imread(path_output)

for interest_configuration in tqdm(img_interest_size, desc="Benchmarking chroma key"):
  img_inp = cv2.resize(deepcopy(img_inp_o), (interest_configuration, interest_configuration))
  img_back = cv2.resize(deepcopy(img_back_o), (interest_configuration, interest_configuration))

  tracemalloc.start()
  chroma_key(img_inp, img_back, custom_change_color, 40)
  current, peak = tracemalloc.get_traced_memory()
  tracemalloc.stop()
  peak = peak / 1024 / 1024


  t = timeit.timeit(
      lambda: chroma_key(img_inp, img_back, custom_change_color, 40),
      number=10
  )
  t /= 10

  result_df[f"interest_configuration_{interest_configuration}"] = {
      "time": t,
      "memory_peak": peak,
      "memory_current": current / 1024 / 1024
  }

pd.DataFrame(result_df)

